name: clang-format-command

on:
  pull_request:
    paths:
      - '**.cxx'
      - '**.hxx'

jobs:
  clang-format:
    runs-on: ubuntu-latest
    steps:
      # Checkout the pull request branch, also include all history
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      # This also installs git-clang-format
      - name: Install clang-format
        run: sudo apt install clang-format

      - name: Run clang-format
        id: format
        run: clang-format $(git ls-tree --name-only HEAD | grep xx\$) -i

      - name: Commit to the PR branch
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Apply clang-format changes"

